version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongo-sandbox
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: